### ISSUE TITLE
Multiple SSH connections with single gateway instance and same server and client agent not working

### ISSUE THREAD

**Issue by simran3695** [Enterprise-connect/ec-x-sdk#100]
if we stop 2 out of 3 running GW’s, client – server communication is not re-established but getting a “bad handshake” error

**Comment by ayasuda2OO3** [comment]
> if we stop 2 out of 3 running GW’s, client – server communication is not re-established but getting a “bad handshake” error

Some QA will help resolve this issue-
1) what is the step(s) to "stop" the gateway instances, as specified, 2 out of 3?
2) is there a superconn remained, given 2 out of 3 are off?
3) did the "bad handshake" error happen during the current ssh session? or-
4) have you tried to establish a new ssh session, assuming a broken ssh session already in place?

Lastly, some logs/screenshots would be helpful to further the investigation effort. @simran3695

**Comment by ramaraosrikakulapu** [comment]
@ayasuda2003 .. @simran3695 created this issue based on demo session and here are the few more details - 

- Run gateway in watcher mode in a VM with 3 instances 
- Run the server agent with rpt 22 and it created super connection with all 3 gateway instances
- Run client on custom port and connection is fine 
- Now bring down 2 gateway instances by killing the gateway containers by ```docker rm contain-id -f``` command. Now only one gateway container is running under watcher
- Do not restart server and client agents
- Create SSH tunnel from client host by running ```ssh user@clienthost -p clientport``` and it went fine
- Open other SSH tunnel from other terminal by running the same command ```ssh user@clienthost -p clientport``` without stopping the first tunnel and now it gives "bad handshake' error

Hope this helps !!

**Comment by ayasuda2OO3** [comment]
Thanks for the detail @ramaraosrikakulapu 

The watcher currently adopts and implemented the OCI Runtime Spec. Removing a runtime container defeating the purpose of the self-recovery as one element of OCI container spec (restarting policy->always) That's also beyond the scope of the OCI container usage.

The **restarting policy->always** means as a OCI container, under any circumstances (memory leaks, incorrect usage, bad software practice, etc.) **should recover by itself** given the policy as part of the Runtime spec. [1]

In the event of scaling, making CF as an example, we scale up/down by indicating the number of instances in CF commands. Similarly, the scaling on the number of gateway instances must be completely transparent and known to the watcher prior to any events taken place (increase/decrease, memory/storage usage, etc.) This cannot be unexpected, and must be in-control by the guest system.

Please **propose a connectivity behaviour/issue that meet the OCI Runtime Spec**, we will address any issues with proper solutions. @simran3695 

**The ability of auto-scaling in watcher is not currently implemented** and may soon be discussed in feature planning.


Reference:
[1] [OCI Runtime Spec](https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks)

**Comment by ayasuda2OO3** [comment]
Issue will close in next three day for the inactivity. @simran3695

**Comment by ramaraosrikakulapu** [comment]
Here are my findings - 

- Running the watcher with 3 gateway instances in a VM
- EC service registered all 3 gateway instances
- Tried to kill the gateway process from container with the following command - 
```
docker exec -it container-id ps -ef | grep agent
docker exec -it container-id kill -9 proc-id
``` 
- Still able to see the container and working normal
- From the conversations, we should not use ```docker rm container-id``` to verify the gateway recover functionality, as it is manual activity and container wont come back automatically for forceful activity. Containers will come back only if gateway process git killed within container due to some reason.

**Comment by ayasuda2OO3** [comment]
Close for the clarity. @ramaraosrikakulapu @simran3695
