### ISSUE TITLE
Modify field scope in UserDetails 

### ISSUE THREAD

**Issue by Gayatri212** [Enterprise-connect/ec-x-sdk#107]
### Purpose
- To get multiple scopes from userDetail for providing access to UI

### What to do
- Currently the scope field in UserDetails is taking string value
- Modify this to array of string so that multiple scopes can be added for one user

**Comment by ayasuda2OO3** [comment]
Proposal accepted. In progress. @Gayatri212

**Comment by Gayatri212** [comment]
Closed due to duplicate. Track this here #112
