### ISSUE TITLE
Watcher is not considering EC_CSC env variable to launch 

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#111]
Passphrase set to the env variable EC_CSC with the command ```export EC_CSC=passphrase-secret``` (passphrase-secret replaced with original secret) 

Then trying to launch the watcher with the command ```./agent -cfg config.yml -wtr```, but still asking for passphrase

Expecting ```./agent -cfg config.yml -wtr``` command will read the value from EC_CSC env variable and proceed to launch watcher without user input.

Please advise, if I am doing any mistake

**Comment by ayasuda2OO3** [comment]
EC_CSC may only take the encrypted time-specific string generated by the agent. Notting the output of the encrypted string will expire in 20mins. 

To ensure the un-interruption, you may schedule a job to overwrite the EC_CSC as following example-
```bash
export EC_CSC=$(cat ~/path/to/client_secret)
```
An authenticated agent will renew the client_secret prior to the expiry.

**Comment by ayasuda2OO3** [comment]
#### proposed usage
```bash
# if the env var $EC_CSC is valid, 
# the agent will refresh/generate the secret. 
# Otherwise it will ask passphrase in stdin
./agent -rfs 
```

**Comment by ramaraosrikakulapu** [comment]
Thanks @ayasuda2003 . Now watcher is trying to start after passing the encrypted token. but facing a problem to launch watcher and I will track it [here](https://github.com/Enterprise-connect/oci/issues/6). 

Also I have to create job for refresh it regularly.

Since the purpose of this issue is met and got the solution, I am closing this issue.
