### ISSUE TITLE
EC Service crashing frequently

### ISSUE THREAD

**Issue by vrp0000** [Enterprise-connect/ec-x-sdk#128]
EC connection failing frequently with the below in the logs
"no gateway info found in list".
404 Not found:Requested Route to <zone-id> does not exist.
On checking further we found that EC service for a particular zone is crashing frequently.
Please check the cause of the crash of the service and a resolution for it

**Comment by ayasuda2OO3** [comment]
Thanks for the tracker. We acknowledged the issue,  will give update soon. WIP.

**Comment by ayasuda2OO3** [comment]
Action items:
1) identify the cause looking at the event in the CF, 
2) scale up the service app.

@Gayatri212 @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
- It is running with 3 instances so far and scaled up to 5
- Looked at the crash report and noticed every instance is getting crashed one time in a day. But minimum 2 instances are always running

**Comment by ayasuda2OO3** [comment]
@vrp0000 please share feedback. FYI This issue may be closed by the stale bot due to inactivity. @ramaraosrikakulapu @Gayatri212
