### ISSUE TITLE
Failed in Restage/Restart Agents deployed in Predix Cloud Foundry CF1

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#15]
Some reports indicate as of today (Oct-10-2019) that when restarting agents, the Cloud Foundry would raise exception as following-

![thumbnail_image001](https://user-images.githubusercontent.com/552253/66587905-37e99500-eb40-11e9-8480-2463450cebd0.png)
![thumbnail_image002](https://user-images.githubusercontent.com/552253/66587906-37e99500-eb40-11e9-8526-cee1411cdbd8.png)

Our initial assessment is that the Cloud Foundry stack may not be compatible with the latest binary servicepack. This is an ongoing issue.

**Comment by ramaraosrikakulapu** [comment]
Announcing the End-of-Life for cflinuxfs2 - 
https://blog.anynines.com/announcing-the-end-of-life-for-cflinuxfs2/
Looks like we need to start using cflinuxfs3, but stack needs to be installed

**Comment by ayasuda2OO3** [comment]
@ramaraosrikakulapu thanks for the advice. should we tag someone from predix in this issue? it may require some upgrade. In the interim, can a servicepack downgrade resolves this issue temporally? @Gayatri212 @palokam @plake06

**Comment by ramaraosrikakulapu** [comment]
Predix support team had suggested to use "https://github.com/cloudfoundry/binary-buildpack.git#v1.0.32" buildpack in manifest. Ekansh had created the ticket INC0094107 in predix.io for the same and Ops team confirmed gateway app deployed fine.
