### ISSUE TITLE
Idea: End to end health probe across EC Agent layers

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-x-sdk#17]
**Issue:**  
There is NO quick Health Check to know complete communication between all Client-> Gateway -> Server agents

**Description:**
Typically EC Client only makes a call when the requester makes a call to the resource. But it has a potential to fail because of several reasons(network between client and EC Gateway or backend EC Server issues etc). This put all the burden of connectivity on the requester to handle EC failures.

- Idea is to provide the frequent (5 minutes interval ) health probe connection between all agents EC Client initiated health check between all agents EC-Client > EC GW > EC Server etc
- Health probe refresh interval value can be configured on EC Client side in the future
- This information is stored in an API on the EC Client side - e.g. /connection-health
- Health probe could be as simple as small payload data( sending a timestamp, agentid etc to the other side) that can be sent using file-upload then down-load functionality
- This health information can be used to send proactive alert notifications

**Comment by ayasuda2OO3** [comment]
Addressed in watcher releases.
