### ISSUE TITLE
 - User Guide Needed

### ISSUE THREAD

**Issue by ayasuda-ge** [Enterprise-connect/ec-x-sdk#170]
As a new EC user, I would like to understand how to deploy and to use EC connectivity as-a-service, so that it would apply in my business use case.

**Comment by ramaraosrikakulapu** [comment]
Created [PR](https://github.com/EC-Release/sdk/pull/171) for user guide with initial version. Please feel free to add comments for betterments. @ayasuda-ge @Puja129
