### ISSUE TITLE
Jobs are getting stuck post v210 binaries upgrade on production

### ISSUE THREAD

**Issue by Harshada19** [Enterprise-connect/ec-x-sdk#19]
Team has recently upgraded the libraries on below path and post that the jobs are getting stuck, team need to manually push the adhoc frequently.

Go\src\github.build.ge.com\BHGE-RealTrack\rt-dataIngestion-develop\ec-sdk

ecagent_linux_var
ecagent_darwin_var
ecagent_linux_sys

Services:
rt_bhge_dataloader_prod
rt-dataingestion-jobs_ONG

Kindly help us to address this issue.

Predix ticket raised: Ticket #INC0094247

Thanks and Regards,
Harshada Gawde

**Comment by palokam** [comment]
@Harshada19, Release 212 specifically address this issue with EC Client. We have found a bug on EC Client for long running connections.

I would you encourage start getting 212 in your development quickly.

**Comment by ayasuda2OO3** [comment]
Per @palokam the [newer release #212](https://github.com/Enterprise-connect/ec-x-sdk/releases/tag/v1.hokkaido.212) @Harshada19
