### ISSUE TITLE
Getting "no content" error while creating new Agents

### ISSUE THREAD

**Issue by Uthappa-AR** [Enterprise-connect/ec-x-sdk#191]
While creating new EC Agents we are Getting "no content" error, while using POST Call.

**Comment by ramaraosrikakulapu** [comment]
Upon the initial investigation - 

- Swagger API is unable to execute the API's 
- Same API are running fine with curl command

**Comment by ramaraosrikakulapu** [comment]
Please reopen the issue, if the problem still exists
