### ISSUE TITLE
links to build.ge

### ISSUE THREAD

**Issue by philipwofford** [Enterprise-connect/ec-x-sdk#2]
there are links to build.ge github

**Comment by philipwofford** [comment]
Sorry, having a hard time referencing: https://github.com/Enterprise-connect/ec-x-sdk/blob/v1beta/README.md

it's the line that says 'see our internal....'

**Comment by ayasuda2003** [comment]
Need more context.. is this usage document no longer maintained? https://github.com/Enterprise-connect/documentation

**Comment by philipwofford** [comment]
Sorry, Chia, I meant this line:

> The internal instruction available here entails the building process for the agent binary in this sdk.

It contains a link to build.ge from gitbhub.com

**Comment by ayasuda2OO3** [comment]
close this issue as it irrelevant to external users.
