### ISSUE TITLE
Could not able to make EC connection with beta agent

### ISSUE THREAD

**Issue by rishisoni25** [Enterprise-connect/ec-x-sdk#24]
We were using beta 1676 agent version for making VLAN connection and could not able to make it connection successful.

**Comment by ramaraosrikakulapu** [comment]
Thank you @rishisoni25 for raising the issue.

We recommend to use the latest version 1724 for testing the VLAN connection in beta environment.

**Comment by ayasuda2OO3** [comment]
Thanks for raising the issue. @rishisoni25

Please specify **the use case detail, client/server tool, resources, and screenshots** if needed.
