### ISSUE TITLE
 - How to run Agent in AWS HA

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#29]
How to deploy [the latest gateway agent #212](https://github.com/Enterprise-connect/ec-x-sdk/releases/tag/v1.hokkaido.212) to a AWS EC2 to achieve HA (High-Availability)? What are the steps/instruction.

**Comment by ramaraosrikakulapu** [comment]
Thanks @ayasuda2003 for raising the issue and here are the steps to follow for running the agent in AWS HA - 

1) Provision the EC2 instances in multiple regions with following configuration - 

T2.small
Memory – 4 GB  (2X)
Disk – 4GB (2X)

2) SSH into the first EC2 instance and download the agent binary from github - 
curl https://raw.githubusercontent.com/Enterprise-connect/ec-x-sdk/v1.hokkaido.212/dist/ecagent_linux_sys.tar.gz -o ecagent_linux_sys_212.tar.gz

3) Untar the gz file - 
tar -xvzf ecagent_linux_sys_212.tar.gz

4) Create agent.yml file with EC configuration

5) Repeat the steps 2 to 4 for other EC2 instances

6) Create the load balancer and upload the SSL certs for secure connection

7) Create the target group and register EC2 instances on port that agent listens

8) Create the rules and redirect traffic to the target group

9) Launch the following command in each EC2 instance - 
./ecagent -cfg agent.yml

**Comment by ayasuda2OO3** [comment]
Please continue enhance this steps. @ramaraosrikakulapu
