### ISSUE TITLE
 - Multiple Proxy Settings 

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#30]
Recent deployment indicate several use cases for different proxy settings. E.g. Connecting to a gateway deployed onprem without a HTTP proxy, but still need to be able to access any external CF UAAs/EC Services with separate proxy settings.

**Comment by ramaraosrikakulapu** [comment]
I have couple of options to propose - 

- We should have different proxy settings for connecting to UAA and Gateway OR 
- We can try connecting to both UAA and Gateway with and without proxy settings, though -pxy flag enabled.

**Comment by ayasuda2OO3** [comment]
Acknowledged. Working to get the requirement. In Design phase. ETA is one sprint. **Will need to define a AHA Feature once it is committed**.

**Comment by ayasuda2OO3** [comment]
Confirmed by the stakeholders. In progress.

**Comment by ayasuda2OO3** [comment]
v1beta #1725 is in QA stage. @ramaraosrikakulapu

**Comment by ayasuda2OO3** [comment]
Closed. Proxy usage has been addressed in [release 2730](https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.fukuoka.2730)
