### ISSUE TITLE
Where are the internal/external reference docs link for GE Power Engaging?

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#34]
As a solution engineer I would like to access all links/resources as follows-

1) Rally Stories.
2) AHA Features/Ideas.
3) Repos (Gitlab/Github)
4) Automation (CI/CD)
4) Box.
5) Confluence.
6) Others. etc. 

 Please advise.

**Comment by ramaraosrikakulapu** [comment]
Here are the related links for engagement - 

Rally - https://rally1.rallydev.com/#/60798192667d/detail/userstory/353294792668
Lucidchart - https://www.lucidchart.com/documents/edit/87041f48-a01d-4085-a57d-1820122c6ff5/kqNc~85CYVxz
AHA Features/Ideas - https://ge-dw.aha.io/features/DTEC-85
Box - https://ge.ent.box.com/folder/83160883402

We will add/update the links when needed.
