### ISSUE TITLE
What is the Problem(s) to solve for GE Power?

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#35]
As a solution engineer, what is the problem I would like to solve and the solution I would like to contribute to the GE Power business?

**Comment by ramaraosrikakulapu** [comment]
Here are the actions completed so far - 

- Deployed the manual AWS gateway in EC2 instance in Power VPC
- Created the internal load balancer in power VPC
- DNS request completed with internal load balancer URL to Gateway name
- Certs request completed and uploaded in power VPC (Yet to test)

3 scenarions to test - 
- [Scenario 1](https://github.com/Enterprise-connect/ec-x-sdk/issues/39): 
  - Deploy Server and Gateway agents in Power AWS VPC
  - Deploy Client agent in other EC2 instance in same VPC
- [Scenario 2](https://github.com/Enterprise-connect/ec-x-sdk/issues/40):
  - Deploy Server and Gateway agents in Power AWS VPC
  - Deploy Client agent in other EC2 instance in other VPC
- [Scenario 3](https://github.com/Enterprise-connect/ec-x-sdk/issues/46):
  - Deploy Server and Gateway agents in Power AWS VPC
  - Deploy Client agent in 'On Prem'

**Comment by ramaraosrikakulapu** [comment]
As of Dec 18 2019, Scenario 1 and 2 are tested and able to make connections between server and clients as expected.
