### ISSUE TITLE
 - Create separate AWS subnets and security group comps for deployment purpose

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#41]
Moving the xcalr auto-deployment to the us-east-1. Need the ability to demonstrate the deployment in the designated az. 

Current status:
- all subordinated AWS comps from the automation were still with a wrong az (ohio east)
- Updated aws subnets/security group for the "us-east-1" deployment purpose.

**Comment by ramaraosrikakulapu** [comment]
Will work on it soon

**Comment by ramaraosrikakulapu** [comment]
@ayasuda2003 .. xcalrii application is able to connect to us-east-1 region and created target groups, rules and EC2 instances. 

We can close this issue once we clean the tested components which needs your help.

**Comment by ramaraosrikakulapu** [comment]
Closing the issue as main features already implemented. Cleaning can take place at one time.
