### ISSUE TITLE
EC Logs understanding

### ISSUE THREAD

**Issue by 503025235** [Enterprise-connect/ec-x-sdk#47]
Hi Team,

We experienced EC for Digital Prod went down this weekend and the error we received in EC Server logs as below.

[github.build.ge.com/212359746/wzcore.(*Server).Hire.func2.1 interface conversion: interface {} is nil, not string]. 

Just FYI we also has Cloud foundary outage this weekend. Please help us understand when do we receive such errors because with this error EC Server went down.

Regards.,
Simran

**Comment by ayasuda2OO3** [comment]
Thank you for the detail, @503025235 Simran.

We have a [continue effort as part of the logging enhancement here](https://github.com/Enterprise-connect/ec-x-sdk/projects/1#card-30753121)

Could you share more lines both before/after this line from the logging for more clarity?

> Hi Team,
> 
> We experienced EC for Digital Prod went down this weekend and the error we received in EC Server logs as below.
> 
> [github.build.ge.com/212359746/wzcore.(*Server).Hire.func2.1 interface conversion: interface {} is nil, not string].
> 
> Just FYI we also has Cloud foundary outage this weekend. Please help us understand when do we receive such errors because with this error EC Server went down.
> 
> Regards.,
> Simran

**Comment by ayasuda2OO3** [comment]
Close due to lack of activity,
