### ISSUE TITLE
EC Connectivity Issue for QA2 Instance of PowerPLM

### ISSUE THREAD

**Issue by sjannela-TC** [Enterprise-connect/ec-x-sdk#49]
When we are trying to connect to QA2 Instance from EC we are facing below issue.

Actions Performed:
1.	Instead of load balancer URL , Tried connecting to IP - 10.93.224.23
2.	Tried with IP and Port – 80 and 443
3.	Tried with removing existing QA2 Certificates and re-installation of the certificates provided by Andrew

invokehttp.request.url
http://10.242.49.126:7220/powerplminternal/resources/external/governance/eccn/update
No value set
invokehttp.status.code
502
No value set
invokehttp.status.message
Bad Gateway

Actual URL:https://qa2-powerplm.pw.ge.com/powerplminternal/resources/external/governance/eccn/update

**Comment by ramaraosrikakulapu** [comment]
Thanks for raising the issue @sjannela-TC 

Can you please check the health status of your gateway. Please start, if gateway is not running.

**Comment by ayasuda2OO3** [comment]
Thanks for the detail. Assuming the following use case-

Nifi Instance (requestor)<--> client (aws) -> gateway (aws) <- server (unknown) <--> tcp resource

Please identify the following-

- Agent Rev.
- A workable Gateway ```https://<Gateway-Host>/health``` URL relevant to this troubleshooting.


Please reach out to the **Ops Support group (DigitalGeleguaSupport@ge.com)** if this is a  AWS configuration issue.

**Comment by ayasuda2OO3** [comment]
Close due to lack of activity.
