### ISSUE TITLE
Bug: EC server health and super connection exists but connectivity breaks

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-x-sdk#5]
[EC Server] 2019/09/27 12:48:27 [gateway connection{host=wss://capital-preprod-ec-gateway.run.aws-usw02-pr.ice.predix.io/agent, session=9AXjuhf9xg,gatewayId=dd058d65-56bb-4fa2-bb7c-f365f16f9b41} established for client# Huzils with bindId#YvNk2g7TPf, to VLAN address: 127.0.0.1:7987 if -vln is enabled.]
 [EC Server] 2019/09/27 12:48:27 [websocket is found in the pool for clientId#Huzils]
 [EC Server] 2019/09/27 12:48:27 [successful added resource (alpi2cosbsvn02.corporate.ge.com:7201) for clientId# with bindId#]
 [EC Server] 2019/09/27 12:48:27 [session# 9AXjuhf9xg created. client has been picked from the pool. Beginning two-way piping.]
 [EC Server] 2019/09/27 12:48:27 [connection has been picked up and removed from the pool with bindId#YvNk2g7TPf]
 [EC Server] 2019/09/27 12:48:31 [client#Huzils requests connection with the bind id#s1WvAC5XLC.]
 [EC Server] 2019/09/27 12:48:31 [proxy serivce (10.114.19.201) is found.]
 [EC Server] 2019/09/27 12:48:31 [server has been successfully created for clientId#Huzils with bindId#s1WvAC5XLC]
 [EC Server] 2019/09/27 12:48:31 [gateway connection{host=wss://capital-preprod-ec-gateway.run.aws-usw02-pr.ice.predix.io/agent, session=KIUoYO7gKy,gatewayId=dd058d65-56bb-4fa2-bb7c-f365f16f9b41} established for client# Huzils with bindId#s1WvAC5XLC, to VLAN address: 127.0.0.1:7987 if -vln is enabled.]
 [EC Server] 2019/09/27 12:48:31 [websocket is found in the pool for clientId#Huzils]
 [EC Server] 2019/09/27 12:48:31 [successful added resource (alpi2cosbsvn02.corporate.ge.com:7201) for clientId# with bindId#]
 [EC Server] 2019/09/27 12:48:31 [session# KIUoYO7gKy created. client has been picked from the pool. Beginning two-way piping.]
 [EC Server] 2019/09/27 12:48:31 [connection has been picked up and removed from the pool with bindId#s1WvAC5XLC]
 [EC Server] 2019/09/27 12:48:32 [exception occurred in wsocket client reading. err: websocket: close 1006 (abnormal closure): unexpected EOF  (session# GS2arkRwT0  bind# ZiF55QnrXU )]
 [EC Server] 2019/09/27 12:48:32 [exception occurred in tcp server reading. err: read tcp 10.93.64.244:44938->10.93.64.244:7201: use of closed network connection  (session# GS2arkRwT0  bind# ZiF55QnrXU )]
 [EC Server] 2019/09/27 12:48:32 [session#: GS2arkRwT0 has been deleted.]
 [EC Server] 2019/09/27 12:48:32 [session#: GS2arkRwT0 has been deleted.]
 [EC Server] 2019/09/27 12:48:34 [client#Huzils requests connection with the bind id#t6iqGR4moB.]
 [EC Server] 2019/09/27 12:48:35 [exception occurred in wsocket client reading. err: websocket: close 1006 (abnormal closure): unexpected EOF  (session# I5WCj1NOML  bind# WJc7l0RUTu )]
 [EC Server] 2019/09/27 12:48:35 [exception occurred in tcp server reading. err: read tcp 10.93.64.244:44946->10.93.64.244:7201: use of closed network connection  (session# I5WCj1NOML  bind# WJc7l0RUTu )]
 [EC Server] 2019/09/27 12:48:35 [session#: I5WCj1NOML has been deleted.]
 [EC Server] 2019/09/27 12:48:35 [session#: I5WCj1NOML has been deleted.]
 [EC Server] 2019/09/27 12:48:37 [exception occurred in wsocket client reading. err: websocket: close 1006 (abnormal closure): unexpected EOF  (session# QFknMS4JBt  bind# RUgJdmx6hF )]
 [EC Server] 2019/09/27 12:48:37 [exception occurred in tcp server reading. err: read tcp 10.93.64.244:44952->10.93.64.244:7201: use of closed network connection  (session# QFknMS4JBt  bind# RUgJdmx6hF )]
 [EC Server] 2019/09/27 12:48:37 [session#: QFknMS4JBt has been deleted.]
 [EC Server] 2019/09/27 12:48:37 [session#: QFknMS4JBt has been deleted.]
 [EC Server] 2019/09/27 12:48:44 [exception occurred in wsocket client reading. err: websocket: close 1006 (abnormal closure): unexpected EOF  (session# YfTLZYH90w  bind# mnSsohlc2a )]
 [EC Server] 2019/09/27 12:48:44 [exception occurred in tcp server reading. err: read tcp 10.93.64.244:44972->10.93.64.244:7201: use of closed network connection  (session# YfTLZYH90w  bind# mnSsohlc2a )]

**Comment by ayasuda2OO3** [comment]
This indicates the resource is unreach-able or unexpectedly exist the connection. The concept of agent usage will soon be replaced by watcher in the next several releases.

**Comment by ayasuda2OO3** [comment]
In some cases when deploy an agent in Cloud Foundry, the healthcheck endpoint would persist the last connectivity information throughout a idling period (months) until a next agent restarts/re-launch. Update this issue to an logging enhancement.

**Comment by ayasuda2OO3** [comment]
Closed fixed.
