### ISSUE TITLE
Connectivity check with beta 1725 version

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#54]
Following are the scenarios to test with beta 1725 version - 

Traditional
Fuse mode server
Fuse mode client
VLAN
TLS

**Comment by ramaraosrikakulapu** [comment]
Status as of now - 

Traditional - Completed and working fine
Fuse mode server - In Progress
Fuse mode client - In Progress
VLAN - In Progress
TLS - Not Started

**Comment by ramaraosrikakulapu** [comment]
VLAN functionality tested successfully. Here is the updated status - 

**Traditional** - _Completed_ and working fine
**Fuse mode server** - _On Hold_ - Need DB credentials to test OR need time from DB owner to test the functionality
**Fuse mode client** - _On Hold_ - Need admin access to install sql client OR waiting for tool to be installed
**VLAN** - _Completed_ and working fine
**TLS** - _Not Started_

**Comment by ramaraosrikakulapu** [comment]
Updated status as of Jan 21 - 

**Traditional** - _Completed_ and working fine
**Fuse mode server** - _On Hold_ - Need DB credentials to test OR need time from DB owner to test the functionality
**Fuse mode client** - _Completed_ and working fine
**VLAN** - _Completed_ and working fine
**TLS** - _In Progress_

**Comment by ayasuda2OO3** [comment]
Can we contribute the test script based on [the qa framework](https://github.com/Enterprise-connect/qa.ec)

> Updated status as of Jan 21 -
> 
> **Traditional** - _Completed_ and working fine
> **Fuse mode server** - _On Hold_ - Need DB credentials to test OR need time from DB owner to test the functionality
> **Fuse mode client** - _Completed_ and working fine
> **VLAN** - _Completed_ and working fine
> **TLS** - _In Progress_

**Comment by ramaraosrikakulapu** [comment]
Scripts uploaded and below is the link to access them - 

https://github.com/Enterprise-connect/qa/tree/aws-gateway-direct/aws-direct

**Comment by ramaraosrikakulapu** [comment]
Fuse mode has problem and fixes are in progress. Fixes will be merged in v1.1beta version?

**Comment by ayasuda2OO3** [comment]
This is a part of the ongoing [v1.1beta QA effort](https://github.com/Enterprise-connect/qa/tree/v1.1beta) All relevant updates will be updated in [the CI](https://travis-ci.com/Enterprise-connect/qa) @ramaraosrikakulapu

**Comment by ayasuda2OO3** [comment]
The issue has been addressed in [release v1.1beta.2730](https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.fukuoka.2730) Closed for production release.
