### ISSUE TITLE
scp with enterprise connect

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#68]
This is for documenting a lesson learnt from an experience for doing scp a file from AWS EC2 machine to an on prem VM.

Here are the environment details - 
- Gateway deployed in predix environment
- EC server agent deployed in on prem VM machine where files supposed to copied to
- EC client agent deployed in AWS EC2 instance where client application 'Thread Connect' dev instance (tc-dev) is running

During the initial setup - 
- EC server agent running with configuration - rht as 'VM ip address'
- scp command as - 
```
scp -P {lpt} -o LogLevel=DEBUG -i "{path to id_rsa}" test.txt gstcadmin@{client host ip}:{remote path}
```

How the issue resolved - 

- EC server script - change rht flag to **localhost** instead of 'VM ip address'
- Change the scp command as  - 
```
scp -P {lpt} -o LogLevel=DEBUG -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "{path to id_rsa}" test.txt gstcadmin@localhost:{remote path}
```
Note {client host ip} replaced with localhost. Now EC client will pass the request as ```gstcadmin@localhost``` to EC server and request will intern consider as login to host where EC server is running.

Added couple of ssh_options (-o params), it will make sure not to add ip address to known_hosts file and checking against it.

**Comment by ramaraosrikakulapu** [comment]
@palokam .. Please check and correct the details as needed

**Comment by palokam** [comment]
@ramaraosrikakulapu - another parameter to add so that it will not write into known_hosts to become a problem is 
scp -i "keyfile"...-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ...

**Comment by ramaraosrikakulapu** [comment]
Thanks @palokam !! Updated the description as suggested and closing the issue.
