### ISSUE TITLE
EC Admin Console (Release 13)

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#69]
### Subject
[AHA DTEC-94 As an Ops, need EC Admin Console - View Status & Dashboard](https://ge-dw.aha.io/features/DTEC-94)
### Owner
Gayatri, Koushik.
### Repo
- [web-ui-backend](https://gitlab.com/digital-fo/connectivity/enterprise-connect/platform-agnostic/webui-api)
- [web-ui-frontend](https://github.com/Enterprise-connect/web-ui)
### Packaging
- [docker registry](https://hub.docker.com/repository/docker/enterpriseconnect/webui)
- [tarball](https://github.com/Enterprise-connect/sdk/tree/v1.1beta/dist/webui)
### Documents | Support KB
- [Wiki](https://github.com/Enterprise-connect/sdk/wiki/Web-UI) ([Rally F63](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797827128), [F65](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797731828))
- [FMEA](https://ge.box.com/s/gtskefe94w0s2uxuxnmarvtlnkt774aa) ([Rally F60](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797051376]))
- [Diagram](#) ([Rally F63](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797827128))
### Track Progress
- [web-ui-frontend](https://github.com/Enterprise-connect/web-ui/projects/1)
- [web-ui-backend](https://github.com/Enterprise-connect/sdk/projects/12)

**Comment by Gayatri212** [comment]
- Modified subscription request data model and apis in xcalr. [MR](https://gitlab.com/digital-fo/xcalrii/-/merge_requests/9)
- Added API endpoints for subscription operations in UI backend 
- Merge UI backend code with latest agent [code](https://gitlab.com/digital-fo/connectivity/enterprise-connect/platform-agnostic/webui-api/-/tree/merged-with-agent) 
- Added swagger document for newly added APIS [here](https://github.com/Enterprise-connect/web-ui/tree/swagger-asset)

**Comment by Gayatri212** [comment]
### Issue
- While running web ui using new agent facing following issue

* Ouath2 logs
```
[predix@predix-devbox webui-api]$ cat ~/.ec/1583823330.connectivity.log
 [EC OAuth x0] 2020/03/10 12:25:30 [[keypair# 12fd119f-1b00-41bf-ab82-85182df9c64f imported.]]
 [EC OAuth x0] 2020/03/10 12:25:30 [[The OAuth2 mode is available via port# 17991]]
 [EC OAuth x0] 2020/03/10 12:26:13 [[github.build.ge.com/212359746/wzapi.(*OAuth2Mode).Start.func3.1 runtime error: index out of range]]
```

* WebUI logs
```
[predix@predix-devbox webui-api]$ cat ~/.ec/1583823346.connectivity.log
 [EC API x0] 2020/03/10 12:25:46 [[v1.1beta.fukuoka.2728]]
 [EC Debug x0] 2020/03/10 12:25:46 [[client secrect (passphrase) created on Tue Mar 10 12:15:08 +0530 2020]]
 [EC API x0] 2020/03/10 12:25:46 [[The API mode is available with port# 17990]]
 [EC Debug x0] 2020/03/10 12:26:13 [[unauthorised access.]]
 [EC Debug x0] 2020/03/10 12:26:13 [[http://localhost:17990/v1.1beta/ec]]
 [EC Debug x0] 2020/03/10 12:26:13 [[a.devId 12fd119f-1b00-41bf-ab82-85182df9c64f]]
 [EC Debug x0] 2020/03/10 12:26:13 [[http://localhost:17991/oauth/authorize?client_id=12fd119f-1b00-41bf-ab82-85182df9c64f&login_hint=%7B%22origin%22%3A%22ec-config%22%7D&redirect_uri=http%3A%2F%2Flocalhost%3A17990%2Fv1.1beta%2Fec&response_type=code&scope=api.auth]]
```

- Browser is looking empty no logs in console @ayasuda2003

**Comment by ayasuda2OO3** [comment]
In [WebUI release.1](https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.webui.1)
