### ISSUE TITLE
Scripts: Provide an easy way to generate all scripts required for EC connectivity (GW , Server, Client) with a simple bash/python script

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-x-sdk#7]
Provide a Bash/Python script to generate the standard scripts after service creation to make it easy for customer to adapt EC

**Comment by ayasuda2OO3** [comment]
addressed in [webui #1 release](https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.webui.1)
