### ISSUE TITLE
Setup Gateway in Azure VPC (Release 13)

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#70]
### Subject
[AHA DTEC-95 Setup Gateway in Azure VPC](https://ge-dw.aha.io/features/DTEC-95)
### Feature Owner
Ram.
### Repo
- [Container Usage in Azure](https://github.com/Enterprise-connect/oci)
### Packaging
- [docker registry](https://hub.docker.com/repository/docker/enterpriseconnect/agent)
- [tarball](https://github.com/Enterprise-connect/sdk/tree/v1.1beta/dist/agent)
### Documents | Support KB
- [Wiki](https://github.com/Enterprise-connect/sdk/wiki/Web-UI) ([Rally F63](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797827128), [F65](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797731828))
- [FMEA](https://ge.box.com/s/gtskefe94w0s2uxuxnmarvtlnkt774aa) ([Rally F60](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797051376]))
- [Diagram](#) ([Rally F63](https://rally1.rallydev.com/#/350544294544d/releaseplanning?qdp=%2Fdetail%2Fportfolioitem%2Ffeature%2F372797827128))

**Comment by ramaraosrikakulapu** [comment]
Provisioned with an ALB (ip address: 10.210.151.229) and Ubuntu virtual machine (ip address: 10.210.151.230).

Able to to run the gateway in Azure VM and able to curl the health page from the same VM, but unable to access health page from outside.

From the discussion, we understood security rules are not allowing to access the gateway health page. Have to work with Zameer to update the security rules on Virtual machine.

**Comment by ramaraosrikakulapu** [comment]
Updated the security rules and able to access the gateway health page from on prem network. 

Next steps:
Recreate them to understand better
Check the EC connection with Azure gateway
Documentation

**Comment by ramaraosrikakulapu** [comment]
Following are the activities to create in order - 
Resource Group
Subnets
Virtual Network
Virtual Machines
Azure Application Gateway
Listener
Routing rule
Http Settings
Health Probes

Deployed EC agent in gateway mode and able to access it with azure application gateway. Yet to test EC connectivity with Azure EC gateway.

**Comment by ramaraosrikakulapu** [comment]
Deployed the gateway in a Azure VM and able to make successful EC connection with server and client agents via 'Azure Load Balancer'.

Documented the steps in [wiki](https://github.com/Enterprise-connect/sdk/wiki/Azure-EC-Gateway) page. Only change, create 'Azure application Load balancer'  instead of 'Azure Application Gateway'.

Closing the issue.

Next release: Achieve HA for gateways by load balancing with NGINX
