### ISSUE TITLE
Fill out FMEA document for EC (Release 13)

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#72]
Fill FMEA document for enterprise connect product to cover multiple failure scenarios, root causes, steps to taken

**Comment by ayasuda2OO3** [comment]
#69 #70 #71 please ensure [the form is updated via here]( https://ge.box.com/s/gtskefe94w0s2uxuxnmarvtlnkt774aa) as [its specified here](https://github.com/Enterprise-connect/sdk/issues/70) @ramaraosrikakulapu 

moved to in-progress.

**Comment by ramaraosrikakulapu** [comment]
Reviewed with @palokam on Mar 13 and explained the planned scenarios to cover in FMEA and got suggestions for improvement.

**Comment by ramaraosrikakulapu** [comment]
Uploaded the latest version in [box](https://ge.ent.box.com/folder/105857736626)

**Comment by ramaraosrikakulapu** [comment]
Took the review comment from @ayasuda2003 and updated FMEA sheet with issues list

**Comment by ramaraosrikakulapu** [comment]
EC FMEA KT given to the ops team on Mar 24. Incorporated comments from audience and updated the tracker. FMEA document available in [box](https://ge.ent.box.com/folder/107935435242)
