### ISSUE TITLE
EC Gateway load balancing across multiple VM's

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#77]
**Requirement**: EC Gateway need to support load balancing across VMs - AWS/Azure

**Requirement:**
- [Aha](https://ge-dw.aha.io/features/DTEC-107)

**Design**
- [Lucidchart](https://www.lucidchart.com/documents/edit/5f94c25c-260a-4bf0-a14a-39b98a9c396a/LO9PsPKXC1ku)

**Packaging**
- [Repository](https://github.com/Enterprise-connect/oci/tree/v1.1beta/spec/loadbalancer)

**Image Registry**
- [Registry](https://hub.docker.com/repository/docker/enterpriseconnect/loadbalancer/general)

**Comment by ramaraosrikakulapu** [comment]
**Design:** 
- Provision VM and run the load balancer
- Run gateway in multiple VM's. Multiple ways to run gateway - 
  - Run along with watcher
  - Run in docker container
  - Run as standalone process
- All gateway instances register with EC service
- Server agent maintain super connection with all gateway instances
- Client should connect to server agent via any gateway instance

**Comment by ramaraosrikakulapu** [comment]
Status as of Apr 15 - 

- 3 VM's provisioned and one used to run load balancer and other 2 allotted for running gateways
- Deployed load balancer (nginx) in a docker container in one VM
- Gateway able to run as standalone process and in docker container
- Able to make successful EC connection when one gateway instance is running

To Do:
- Able to make successful EC connections when multiple gateway instances are running
- Able to run gateway in watcher-traditional mode
- Automate the deployment process

**Comment by ramaraosrikakulapu** [comment]
Where we are now - 

- EC gateway running as traditional standalone process in 2 VM's
- Gateway instances registered fine with EC service
- Running the server agent and here is the format of it - 
```
./agent -mod server -aid {target-agent-id} \
-grp {ec-service-group} \
-cid {uaa-client-id} -csc {uaa-client-secret} -dur 3000 \
-oa2 https://{valid-oauth-uri}/oauth/token \
-hst ws://{gateway-url}/agent \
-sst https://{valid-service-uri} \
-zon {ec-zone-id} \
-rht {target-host-name} -rpt {target-system-portid} -dbg 
```
Note: Please note, hst flag does not have additional path string to identify gateway instance
- EC server made super connection with both gateways and able to see it from the health page
- Running the EC Client and here is the format - 
```
./agent -mod client -aid {source-agent-id} -tid {target-agent-id} \
-grp {ec-service-group} -zon {ec-zone-id} \
-sst https://{valid-service-uri} \
-hst ws://{gateway-url}/agent  \
-cid {uaa-client-id} -csc {uaa-client-secret} -dur 3000 \
-oa2 https://{valid-oauth-uri}/oauth/token \
-lpt :6192 -dbg
```
- Agent version used - v1.1beta.fukuoka.2732
- Client unable to connect target agent consistently. Means, connection is fine some times but not every time.

**Here is what expecting -** 

- When server agent making super connection, noticed a log - 
```
Super connection established for gateway with inst#x0
```
Same log displayed for both gateways
- When client tried to make connection, request reaches to one gateway and server unable to find, which gateway holds the request as it treats both gateways with id **x0**.

**Comment by ayasuda2OO3** [comment]
Known behaviour. Please note one ```server``` cannot not serve across multiple vms. In the use case of vm x2, each server can  ONLY serve one ```vm/vm URL``` given the scaling model. For multiple gateway instances as illustrated below, **server#2** should never reach to neither **gateway#1**, **gateway#2**, or watcher#1, if watcher is in use.

Topology diagram: 
```txt
Lber 
+-- vm1 (URL A)-+
|               +---watcher#1--+-- gateway#1---- \
|                              |                    > server#1
|                              +-- gateway#2---- /  
|
+-- vm2 (URL B)-+
                +---watcher#2--+-- gateway#3---- \
                               |                    > server#2
                               +-- gateway#4---- /  
```

> EC gateway running as traditional standalone process in 2 VM's
@palokam @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
Hi @ayasuda2003  tried the same as suggested. Here are the steps taken - 

- Running the first gateway with ```hst``` - ```ws://{loadbalancer ip}/vm1/agent```
- Running the second gateway with ```hst``` - ```ws://{loadbalancer ip}/vm2/agent```
- Server script with ```hst``` - ```ws://{loadbalancer ip}/vm1/agent``` and super connection established only with gateway running in vm1
- Client with ```hst``` - ```ws://{loadbalancer ip}/agent```, able to make **successful** connection with target agent

So we can make successful EC connection with gateway running in one VM. However, if vm1 is down, server agent can't make super connections and have to change the ```hst``` flag manually in server script.

**Comment by ayasuda2OO3** [comment]
> Hi @ayasuda2003 tried the same as suggested. Here are the steps taken -
> 
> * Running the first gateway with `hst` - `ws://{loadbalancer ip}/vm1/agent`
> * Running the second gateway with `hst` - `ws://{loadbalancer ip}/vm2/agent`
> * Server script with `hst` - `ws://{loadbalancer ip}/vm1/agent` and super connection established only with gateway running in vm1
> * Client with `hst` - `ws://{loadbalancer ip}/agent`, able to make **successful** connection with target agent
> 
> So we can make successful EC connection with gateway running in one VM. However, if vm1 is down, server agent can't make super connections and have to change the `hst` flag manually in server script.

Known behaviour. ```-hst``` in ```mod=server``` is meant to configure for accessing a specific vm. Noting ```-hst``` value cannot be ambiguous between vms/url.

An enhancement is added to gateway filtering- when server validating the gateway list for establishing superconn(s), the ```-hst``` on server config MUST matches **the gateway url in the list**. The purpose of this enhancement that it is **ONE server** is restricted to establishing a number of superconn over **ONE vm/URL**

Please share feedback from testing this patch release.
https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.fukuoka.2733

**Comment by ramaraosrikakulapu** [comment]
Here is the plan to proceed in phase 1 as per discussion on 05/05 - 

- Use one VM behind the load balancer
- Run gateway in watcher mode with multiple instances
- All gateway instances must be registered with EC service
- Server agent must able to make super connection with all gateways
- Client should able to make successful connection to Server agent via any gateway instance

[Design flow](https://www.lucidchart.com/documents/edit/5f94c25c-260a-4bf0-a14a-39b98a9c396a/LdpWN8n43tt-)

**Comment by ramaraosrikakulapu** [comment]
@ayasuda2003 .. I am using 2733 version and trying to run the binary in watcher mode. But getting 'Invalid Header'. 

![watcher](https://user-images.githubusercontent.com/38732583/81187878-a1207200-8f82-11ea-9ea5-af640f00e1a8.png)

Can you please tell me, if I have to make any changes to yml configuration compared to prev versions. #92

**Comment by ayasuda2OO3** [comment]
> @ayasuda2003 .. I am using 2733 version and trying to run the binary in watcher mode. But getting 'Invalid Header'.
> 
> ![watcher](https://user-images.githubusercontent.com/38732583/81187878-a1207200-8f82-11ea-9ea5-af640f00e1a8.png)
> 
> Can you please tell me, if I have to make any changes to yml configuration compared to prev versions. #92

Could you share the ``` gateway.yml```?

**Comment by ramaraosrikakulapu** [comment]
Got the problem @ayasuda2003 .. I have to update the agent version for ```contRev``` in the yml file. That resolved he problem. But taking so long after entering the passphrase and never returned back. Attaching the file here - 

[gateway.yml.zip](https://github.com/Enterprise-connect/sdk/files/4588118/gateway.yml.zip)

**Comment by ramaraosrikakulapu** [comment]
Creating watcher containers issue resolved. Now watcher and all gateway containers are up and running. In progress for enabling the health page and make super connection success with server agents.

**Comment by ayasuda2OO3** [comment]
@ramaraosrikakulapu please share update.

**Comment by ramaraosrikakulapu** [comment]
Updating with latest status - 

- End to end flow with watcher and gateway instances in one VM is working fine. 
- Next target is to run watcher in multiple VM's and all gateway instances must register with EC service
- Server agent should have super connection with all gateways 
- Client should able to make connection to target system via any gateway
- Connection should be seemless, even if any gateway/ watcher/ VM is down

**Comment by ramaraosrikakulapu** [comment]
Updating the points discussed in teams -  
- Removed all existing docker containers and EC network and started every thing fresh. Here are some findings from gateway list - 
- Watcher is running with 3 gateway instances with URL - ws://x.x.1.120/vm1/agent
- All 3 gateway instances registered with EC service with diff gtwid's - xx:xx:xx:xx:10:01, xx:xx:xx:xx:10:02, xx:xx:xx:xx:10:00
- But predix gateway working in diff way. Multiple predix gateway instances registering with same gtwid. ex: ab0200b3-0c28-47e8-8098-b6f4cbf72400
and service URI - https://d985acd4-806a-4679-9441-cd6ebc211c22.run.aws-usw02-dev.ice.predix.io/v1beta/index/#/
- Also, Couple of weeks back, I ran watcher with 3 gateway instances with URL "wss://corp-preprod-ecgw4.apps.ge.com/vm1/agent" for SSL functionality, but still showing in gateway list and using the same gtwid's as ws://x.x.1.120/vm1/agent. List is not going away even after restaging the service instance.


I believe 2 things to point here -
1) Gateways under watcher must use same gtwId as predix gateway and they will get diiferentiated with refId x0, x1, x2..
2) Gateway list must be cleared when they are not running

**Comment by ramaraosrikakulapu** [comment]
As per the discussion today, started running watcher in 2 VM's with one gateway instance each. But EC service is showing only latest gateway instance with same gtwId. 

It looks to me, if watcher in VM1 restarts, EC service will show gateway running in VM1 and later if watcher in VM2 restarts, EC service is overriding with gateway in VM2.

**Comment by ayasuda2OO3** [comment]
> As per the discussion today, started running watcher in 2 VM's with one gateway instance each. But EC service is showing only latest gateway instance with same gtwId.
> 
> It looks to me, if watcher in VM1 restarts, EC service will show gateway running in VM1 and later if watcher in VM2 restarts, EC service is overriding with gateway in VM2.

Thanks for the finding. the key-value pair in the gateway list provisioned by the service api follows the below format-
```json
{
"<vm-mac-addr:x<n,gateway instance index>":
   {
"*":"*"
"CFURL" : "https://xxx.predix.io"

}
"*":"*"
}
```
In another word, the vm1 can only be replaced by vm2 when 1) the vms share a same mac address. && 2) The gateways share a same index.

It is very possible the gateways may use a same index (e.g. x1, x2, etc.) but it wouldn't make sense for the vms using an identical mac address. Based on the inference, please verify in the vm usage. @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
Yup.. Thats a valid point. My 2 VM's are running on boot2docker OS and should not share same mac address. Also mac address shown in EC service is not showing in ```ip a``` output

I will check why both VM's showing same mac address, OR I will use other VM with diff OS to run watcher.

**Comment by ramaraosrikakulapu** [comment]
Here is the reason for same IPv6/mac address for gateways. All EC gateways are registering with container IPv6/mac address where gateway process is running, which are same when running from multiple VM's. In detail - 
  - VM1 is running a watcher with 2 gateway instances and both are registering with IPv6/mac address of gateway containers instead of VM address
  - VM2 is replica of VM1 and running a watcher and 2 gateway instances in containers
  - Unfortunately containers in both VM's shows the same IPv6 addresses - 00:00:00:00:16:00 and 00:00:00:00:16:01 
  
  One solution for this is - 
  - Create docker EC network manually as - 
  ```
  docker network create \
  --driver=bridge \
  --subnet=101.102.0.0/16 \
  --ip-range=101.102.5.0/24 \
  --gateway=101.102.5.254 \
  EC_Network
  ```
  - Run the watcher with command ```./agent -cfg watcher.yml -wtr```
  - Now containers have different IPv6/mac addresses, but would be great, if we can configure that from watcher.yml

**Comment by ayasuda2OO3** [comment]
> Here is the reason for same IPv6/mac address for gateways. All EC gateways are registering with container IPv6/mac address where gateway process is running, which are same when running from multiple VM's. In detail -
> 
> * VM1 is running a watcher with 2 gateway instances and both are registering with IPv6/mac address of gateway containers instead of VM address
> * VM2 is replica of VM1 and running a watcher and 2 gateway instances in containers
> * Unfortunately containers in both VM's shows the same IPv6 addresses - 00:00:00:00:16:00 and 00:00:00:00:16:01
> 
> One solution for this is -
> 
> * Create docker EC network manually as -
> 
> ```
> docker network create \
> --driver=bridge \
> --subnet=101.102.0.0/16 \
> --ip-range=101.102.5.0/24 \
> --gateway=101.102.5.254 \
> EC_Network
> ```
> 
> * Run the watcher with command `./agent -cfg watcher.yml -wtr`
> * Now containers have different IPv6/mac addresses, but would be great, if we can configure that from watcher.yml

Excellent findings and an acceptable solution @ramaraosrikakulapu Watcher has a built-in mac address arrangement in a situation when a container does not pre-configure itself based on the vm. Will incorporate the solution in the next pre-release. ETA for the fix 2-3 days.

**Comment by ramaraosrikakulapu** [comment]
Thanks @ayasuda2003 for working on the changes for configuring IPv6/mac addresses for containers. For now, I am following the additional step for creating the ```EC_Network``` manually and running the watcher in VM2. Here is my environment looks like - 
  - VM1 running a watcher with 2 gateways with hst URL - ```ws://x.x.x.124/vm1/agent``` as suggested in [design ](https://app.lucidchart.com/documents/edit/3f02a4cb-0c4d-46b3-a92a-f40a505004ec/zvdWm9k1abq8?shared=true)
  - Created ```EC_Network``` manually in VM2 with different ```subnet``` and ```ip_range```
  - VM2 also running watcher with 2 gateways with hst URL - ```ws://x.x.x.124/vm2/agent```
  - Now containers in both VM's have different IPv6/mac addresses
  - All 4 gateways are registered with EC service fine with unique combination of ```gtwId:refId```
  - Server agent is running with hst URL ws://x.x.x.124/agent, but unable to make super connection with any of gateway instances
  
  I believe this is because of recent changes in last release, server agent must have exact URL as in gateway and might have to relax the rule now.

**Comment by ayasuda2OO3** [comment]
> Thanks @ayasuda2003 for working on the changes for configuring IPv6/mac addresses for containers. For now, I am following the additional step for creating the `EC_Network` manually and running the watcher in VM2. Here is my environment looks like -
> 
> * VM1 running a watcher with 2 gateways with hst URL - `ws://x.x.x.124/vm1/agent` as suggested in [design ](https://app.lucidchart.com/documents/edit/3f02a4cb-0c4d-46b3-a92a-f40a505004ec/zvdWm9k1abq8?shared=true)
> * Created `EC_Network` manually in VM2 with different `subnet` and `ip_range`
> * VM2 also running watcher with 2 gateways with hst URL - `ws://x.x.x.124/vm2/agent`
> * Now containers in both VM's have different IPv6/mac addresses
> * All 4 gateways are registered with EC service fine with unique combination of `gtwId:refId`
> * Server agent is running with hst URL ws://x.x.x.124/agent, but unable to make super connection with any of gateway instances
> 
> I believe this is because of recent changes in last release, server agent must have exact URL as in gateway and might have to relax the rule now.

The server setting must follows the ```-hst``` field configured on the watchers. The ```-hst ws://x.x.x.124/agent``` configured on server implies lbcing the server traffic which does not serve the purpose as per design. Please update in usage. FYI the macaddr arrangement on watcher is WIP.

**Comment by ramaraosrikakulapu** [comment]
It implies ```hst``` URL in server configuration must be ```ws://x.x.x.124/vm1/agent``` or ```ws://x.x.x.124/vm2/agent```.. correct @ayasuda2003 ?

**Comment by ramaraosrikakulapu** [comment]
I am trying to run watchers with gateway URLs - ```ws://x.x.x.124/vm1/agent``` and ```ws://x.x.x.124/vm2/agent``` and following things can happen - 
- Server agent at a time can connect to one watcher as it has to use ```ws://x.x.x.124/vm1/agent``` or ```ws://x.x.x.124/vm2/agent```
- Other option is "should run 2 server agents with diff agent id's in target env"  and each server agent will connect to one watcher. But client can connect to only one server agent, as we can pass only one id to ```tid``` flag in client configuration.

**Comment by ayasuda2OO3** [comment]
> I am trying to run watchers with gateway URLs - `ws://x.x.x.124/vm1/agent` and `ws://x.x.x.124/vm2/agent` and following things can happen -
> 
> * Server agent at a time can connect to one watcher as it has to use `ws://x.x.x.124/vm1/agent` or `ws://x.x.x.124/vm2/agent`
> * Other option is "should run 2 server agents with diff agent id's in target env"  and each server agent will connect to one watcher. But client can connect to only one server agent, as we can pass only one id to `tid` flag in client configuration.

The prior aligns the current usage. The 2 server agents in the latter can both pointed to the same resource. The client traffic should be **guaranteed** to distribute evenly amongst the servers by the LBer.

**Comment by ramaraosrikakulapu** [comment]
Can you please be more specific, how the ```hst``` URL supposed to be in watcher config and server config and how many servers to run when 2 watchers are running?

I believe client for sure will use ```ws://x.x.x.124/agent``` for making connections.

**Comment by ayasuda2OO3** [comment]
> Can you please be more specific, how the `hst` URL supposed to be in watcher config and server config and how many servers to run when 2 watchers are running?
> 
> I believe client for sure will use `ws://x.x.x.124/agent` for making connections.

it had been [answered here](https://github.com/Enterprise-connect/sdk/issues/77#issuecomment-622608260)

Yes, your belief on the client setting is correct.

**Comment by ramaraosrikakulapu** [comment]
(Updated on June 1)
Hi @palokam, From our discussion - 

- We are going to have common gateway hst URL for all gateway's running across VM's as ```ws://x.x.x.124/agent``` and no more ```ws://x.x.x.124/vm1/agent``` or ```ws://x.x.x.124/vm2/agent```. 

- Server agent have to make super connection with all gateway instances

- Client will choose any path based on load balancer rule.


Topology diagram: 
```txt
Lber 
+-- vm1 (URL A)-+
|               +---watcher#1--+-- gateway#1---- \
|                              |                  \
|                              +-- gateway#2---- \ \
|                                                 \ \
+-- vm2 (URL B)-+                                     > server
                +---watcher#2--+-- gateway#3---- /   /
                               |                    /
                               +-- gateway#4----   /  
```

**Comment by ayasuda2OO3** [comment]
> (Updated on June 1)
> Hi @palokam, From our discussion -
> 
> * We are going to have common gateway hst URL for all gateway's running across VM's as `ws://x.x.x.124/agent` and no more `ws://x.x.x.124/vm1/agent` or `ws://x.x.x.124/vm2/agent`.
> * Server agent have to make super connection with all gateway instances
> * Client will choose any path based on load balancer rule.
> 
> Topology diagram:
> 
> ```
> Lber 
> +-- vm1 (URL A)-+
> |               +---watcher#1--+-- gateway#1---- \
> |                              |                  \
> |                              +-- gateway#2---- \ \
> |                                                 \ \
> +-- vm2 (URL B)-+                                     > server
>                 +---watcher#2--+-- gateway#3---- /   /
>                                |                    /
>                                +-- gateway#4----   /  
> ```

The separate requirement is specified in #109 (HA across vms), please document this comment in #109 . This issue will close in next couple of days if no more activity

**Comment by ayasuda2OO3** [comment]
Close for duplicate #109
