### ISSUE TITLE
EC Performance metrics

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#78]
Get the performance metrics with 2725 version across platforms

**Comment by ayasuda2OO3** [comment]
Please provide an update if any, otherwise will soon be closed due to the inactivity. Thanks! @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
### Use case Scenario
- Deploy database high volumes of records in on prem
- Deploy gateway in multiple platforms (Predix, AWS and Azure)
- Run server and client agents with gateways from Predix, AWS and Azure

### Environment
- Deployed postgres database with 65400+ records
- Deployed multiple gateways in Predix CF3, AWS Power VPC and Corp Azure Subscription
- Running the server and client agents in 'on prem' with different gateways

### Results
Below are the results noticed to run the query and fetch 65400+ records - 

| Source | Time to run the query in Secs |
| ------- | --------------------- |
| Direct query on DB | 100 |
| Predix Gateway | 122 |
| AWS Gateway | 102 |
| Azure Gateway | 118 |

**Comment by ramaraosrikakulapu** [comment]
Closing the issue as results are updated.
