### ISSUE TITLE
 - Usage Validation Enhancement

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#8]
Current validation process is painfully long.

Create a background validation process to 1) fetch the group information 2) persist the group information in memory.

**Comment by palokam** [comment]
- This will also help the connectivity issues, when  any EC service intermittent issues in CF or network communication issues with the internet from EC Gateway. #ECgateway

- #ECGW need an additional cache to verify is UAA token validation results came from previous EC service call to verify JWT Token from  #ECClient and #ECServer - This will help validate speed up the process and any UAA connectivity issues can be resilient  as well.

**Comment by ayasuda2OO3** [comment]
in release.
