### ISSUE TITLE
vlan failure

### ISSUE THREAD

**Issue by vrp0000** [Enterprise-connect/ec-x-sdk#87]
1. We are unable to connect to pqr-scan.com via vlan plugin.
Host :  pqr-scan.com
port : 1525
Getting connection refused in the server logs 

 [EC Server] 2020/04/20 01:35:35 **[github.build.ge.com/212359746/wzcore.(*Server).addResourceInst.func1.1 dial tcp x.y.z.20:6192: connect: connection refused]**
 [EC Server] 2020/04/20 01:35:35 [github.build.ge.com/212359746/wzcore.(*Server).adminPingHandler.func1.2.1 failed to add resource for bindId: QDZZMHZ6oR. the client connection has been removed from the pool.]

2. While using the any of the private IP and private port we are able to connect via dedicated EC.
Private IP1 : a.b.c.53
Private IP2 : a.b.c.54
Private IP3 : a.b.c.55
Private Port : 1526

3. Getting connection refused while connecting to Private IP and Private Port using vlan
IP used : a.b.d.0/24
Port : 1526

**Comment by palokam** [comment]
@ayasuda2003 is the github public repo a good place to share all these details like internal IPs etc?

@vrp0000 - Can you help us understand the plugins.yml in an email to the EC team? **do not post the here**; please remove the previous posting as well, remove all the IPs, you can use convention like x.y.z.53, x.y.z.54, x.y.z.55 use that cryptic information

**Comment by ramaraosrikakulapu** [comment]
@vrp0000 .. From the logs it looks to me, you are trying to connect with client IP and lpt port.
"tcp x.y.z.20:6192: connect: connection refused"

With VLAN, client application should always establish EC connection with Target IP and Target Port. Can you please try and update the result?

**Comment by palokam** [comment]
@vrp0000 and @ramaraosrikakulapu - Getting on a call help speedup the resolution

**Comment by ramaraosrikakulapu** [comment]
@vrp0000 .. Lets have call and close this

**Comment by ayasuda2OO3** [comment]
close due to inactivity
