### ISSUE TITLE
EC Gateway need to support load balancing across VMs - AWS/Azure

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#89]
### Subject
[DTEC-107- EC Gateway need to support load balancing across VMs - AWS/Azure](https://ge-dw.aha.io/features/DTEC-107)
### Packaging
Docker: ```enterprisepriseconnect/loadbalancer:v1.1beta```
### Documents | Support KB | Spec Repo
- [Nginx](https://hub.docker.com/_/nginx)
- [EC Agent wiki](https://github.com/Enterprise-connect/sdk/wiki/EC-Agent)
- [OCI Spec](https://github.com/Enterprise-connect/oci/tree/v1.1beta/spec/loadbalancer)
### Track Progress
- https://github.com/Enterprise-connect/sdk/issues/77

**Comment by ayasuda2003** [comment]
#77

**Comment by ayasuda2003** [comment]
close for duplicate #95

**Comment by ayasuda2OO3** [comment]
close duplicate #77
