### ISSUE TITLE
EC Server TLS plug-in loading is not correct

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-x-sdk#9]
Couple of scenarios

1) When EC server loading for the first time it should check for success of all plug-ins and log that message correctly into EC server logs - when TLS plugin have issues it is still logging a successful TLS plug-in loading message.
     **Steps to reproduce**: Load TLS normally, Kill EC Server process, then TLS process will remain there for some time, when you restart EC Server with TLS plugin, old TLS and new EC Server is not able to handshake because they do not share the same encryption key. eventually old TLS dies, but the log shows every thing was fine, logs should clearly show there is a problem with the TLS not able to start.

2) if the TLS plug-in process got killed for some reason the parent EC Server process should be monitor/watch frequently and log that information and also should try reloading the TLS plugin
     **Steps to reproduce**: Load TLS normally, Kill EC Server process, then TLS process will remain there for some time, when you restart EC Server with TLS plugin, old TLS and new EC Server is not able to handshake because they do not share the same encryption key. eventually old TLS dies, then there has to be an attempt from parent process to start the TLS. 

3) EC server/health should show there is a plugin loaded as well

**Comment by ayasuda2OO3** [comment]
In [usage document](https://github.com/Enterprise-connect/sdk/tree/v1.1beta/plugins/tls)
