### ISSUE TITLE
Unable to make super connection with watcher

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#92]
Here are the steps to recreate the issue - 

- Run watcher in a VM and hst flag as - ws://{IP Addr}:17990/agent
- Run server agent with same hst flag

Server agent is keep trying to make super connection and unable to make it

**Comment by ayasuda2OO3** [comment]
Acknowledged. Test In progress.

**Comment by ayasuda2OO3** [comment]
#95 close for duplication. Addressed in the release
