### ISSUE TITLE
Allow traffic through gateway load balancer

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#95]
This is to log the requirement to allow or deny the traffic from agents via the v1.1beta load balancer.

```enterpriseconnect/loadbalancer:v1.1beta``` image is supposed to load balance the traffic only for beta agents. All release version agents must use ```enterpriseconnect/loadbalancer:v1.1``` image.

**Comment by ramaraosrikakulapu** [comment]
Proposed solution by chia - 

Create a header specific to beta agents, which will use to identify the initiator agent's version and allow the traffic.

![API flowchart example - Page 2 (1)](https://user-images.githubusercontent.com/38732583/81328127-5e39c980-906a-11ea-8349-08107d11de5c.png)

**Comment by ayasuda2OO3** [comment]
> This is to log the requirement to allow or deny the traffic from agents via the v1.1beta load balancer.
> 
> `enterpriseconnect/loabalancer:v1.1beta` image is supposed to load balance the traffic only for beta agents. All release version agents must use `enterpriseconnect/loabalancer:v1.1` image.

```loadbalancer``` hope its just a typo?

**Comment by ayasuda2OO3** [comment]
close duplicate #89
