### ISSUE TITLE
log file names while launching EC agent

### ISSUE THREAD

**Issue by Simran0306** [Enterprise-connect/ec-x-sdk#96]
While launching EC agent on the vm through YAML file, the logs gets generated in the .ec folder. If multiple agents are running on same machine it is difficult to identify logs for one particular EC. It would be helpful if logs are generated with "groupame.log file" or any other identification

**Comment by ayasuda2003** [comment]
Thanks, @Simran0306 for opening the tracker.
Please kindly work with the stakeholders (e.g @Kamalesh, @Gowri, @Ryan @palokam, @Pradeep) , and to provide the **feature link references** from stakeholder systems (e.g. AHA, Rally, Jira, etc) when it becomes available for further R&D/Engineering efforts. @ramaraosrikakulapu

**Comment by ayasuda2003** [comment]
feature request deferred to stakeholders.

**Comment by ayasuda2OO3** [comment]
@simran3695 log files are currently grouped by the combination of modes (client,server, gateway, etc.) and timestamp. Inside a log file, each log line entry labeled by the instance# (x0,x1,..xn), if it were to launch by the watcher. Launch the agent individually is deprecated and placed by the watcher config. **Please share feedback**. If no feedback, this proposal may close in next couple of days for the inactivity. @ramaraosrikakulapu @palokam

**Comment by simran3695** [comment]
Consider we have 2 EC client running on same machine one is A and other is B so if the log file for both is created as client_timestamp.log we won't be able to understand for which client that log is referring to. We need log file to generate as A-Client-timesstamp.log so that we know the log is for A EC Client agent.

**Comment by ayasuda2OO3** [comment]
@simran3695 @Simran0306 will the use case be access different resource each?

**Comment by simran3695** [comment]
both are my account, somehow i was not able to login with 0306 one and i had to create a new id.

**Comment by simran3695** [comment]
As discussed, we would like to propose the log file name to <mode>.<groupname-of-agent>.<timestamp>.log

**Comment by simran3695** [comment]
As discussed, we would like to propose the log file name to (mode.groupname.timestamp.log).

**Comment by ayasuda2OO3** [comment]
Acknowledged. Solution in Progress.

**Comment by ayasuda2OO3** [comment]
[In release #2737](https://github.com/Enterprise-connect/sdk/releases/tag/v1.1beta.fukuoka.2737) @Simran0306 @simran3695

**Comment by simran3695** [comment]
Thankyou for the update.
