### ISSUE TITLE
Watcher not bringing gateway that is down

### ISSUE THREAD

**Issue by Simran0306** [Enterprise-connect/ec-x-sdk#98]
We saw a scenario where on a VM if there is a watcher and 3 gateway instances and if one is put down forceully the watcher was not able to bring it back to functional mode. How can we ensure all the gateway and the watcher is always up and running.

**Comment by ayasuda2OO3** [comment]
@Simran0306 
> ..and if one is put down forceully..

can it be more specific?

**Comment by simran3695** [comment]
> @Simran0306
> 
> > ..and if one is put down forceully..
> 
> can it be more specific?

**Comment by simran3695** [comment]
During the demo we had one VM instance where watcher and 3 gateway instances were running. And we forcefully brought down one gateway instance to check if the watcher is able to bring it back by itself. But we din't saw it happen. So in such cases how can we ensure that all instances will be always active. And also if any one goes down how we will be notified.

**Comment by ayasuda2OO3** [comment]
> During the demo we had one VM instance where watcher and 3 gateway instances were running. And we forcefully brought down one gateway instance to check if the watcher is able to bring it back by itself. But we din't saw it happen. So in such cases how can we ensure that all instances will be always active. And also if any one goes down how we will be notified.

Thanks for the detail. Understand we are trying to shutdown instances. What did we do to shutdown the instance(s)? or restart the container(s)? or to completely kill the container(s)? what was the cmd used to shutdown the instance(s)  this will help us to design a proper solution to the said issue. @simran3695

**Comment by ayasuda2OO3** [comment]
Close duplicate #100
